// src/components/Footer.vue
<template>
  <div>
    <footer>
      <p>© {{ new Date().getFullYear() }}</p>
      <a href="https://www.linkedin.com/in/raphael-baguelin" target="_blank">
        <img src="/linkedin.svg" width="26px" alt="Icon LinkedIn" />
      </a>
      <a href="https://github.com/raphbag" target="_blank">
        <img src="/github.svg" width="26px " alt="Icon Github" />
      </a>
    </footer>
  </div>
</template>

<style scoped>
div {
  background-color: #333;
  color: white;
  border-top: 1px solid #ccc;
}

footer {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 50px;
  height: 100%;
}

footer a {
  display: flex;
  align-items: center;
}

img {
  margin-left: 10px;
}
</style>

// src/components/Footer.svelte
<script>
	import { onMount } from 'svelte';

	let currentYear;
	onMount(() => {
		currentYear = new Date().getFullYear();
	});
</script>

<footer>
	<p>&copy; {currentYear}</p>
	<a href="https://github.com/raphbag">
		<img src="/github.svg" width="26px " alt="Icon Github" />
	</a>
</footer>

<style>
	footer {
		display: flex;
		justify-content: center;
		align-items: center;
		padding: 10px 0px;
		background-color: #f0f0f0;
	}

	img {
		display: flex;
		justify-content: center;
		margin-left: 10px;
	}
</style>
