// src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
</script>

<template>
  <div>
    <header>
      <RouterLink to="/">
        <img alt="Logo RB" class="logo" src="/logo.svg" height="50" />
      </RouterLink>
      <nav>
        <RouterLink to="/" active-class="active">Home</RouterLink>
        <RouterLink to="/projets" active-class="active">Projets</RouterLink>
      </nav>
    </header>
  </div>
</template>

<style scoped>
header {
  display: flex;
  align-items: center;
}

nav {
  padding: 20px;
}

nav > a {
  margin-right: 10px;
  text-decoration: none;
}

nav > a:hover {
  background-color: hsla(223, 100%, 50%, 0.2);
}

.active {
  text-decoration: underline rgba(255, 255, 255, 0.8);
}

img {
  padding: 0px 20px;
  border-right: 2px dotted gray;
}
</style>

// src/components/Header.svelte
<script>
	// JavaScript peut être ajouté ici pour le comportement du composant
	// let name = 'Mon Composant';

	let links = [
		{ href: '/', text: 'Home' },
		{ href: '/projects', text: 'Projets' }
	];
</script>

<header>
	<!-- <div>
		Hello {name}!
	</div> -->
	<img src="/logo.png" alt="Logo R du site" />
	<nav>
		{#each links as link}
			<a href={link.href}>{link.text}</a>
		{/each}
	</nav>
</header>

<style>
	/* Styles spécifiques au composant peuvent être ajoutés ici */
	header {
		display: flex;
		align-items: center;
		padding: 10px 0px;
		background-color: #f0f0f0;
	}

	nav {
		padding: 20px;
	}

	nav > a {
		margin-right: 10px;
		color: black;
		text-decoration: none;
	}

	nav > a:hover {
		color: red;
		transition: color 0.5s;
	}
	img {
		width: 60px;
		padding: 10px 20px;
		border-right: 2px dotted gray;
	}

	img:hover {
		cursor: pointer;
	}
</style>
